version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"

sphinx:
  builder: html
  configuration: docs/source/conf.py

python:
  system_packages: false
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all
